name: Jakarta Rewrite

on:
  workflow_dispatch:
  schedule:
    # 4am every weekday + saturday
    - cron: '0 4 * * 1-6'
jobs:
  rewrite:
    runs-on: ubuntu-latest
    name: Rewrite to Jakarta
    if: github.repository == 'quarkusio/quarkus' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.JAKARTA_PUSH_PAT }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Install JBang
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
        shell: bash
      - name: Transform sources
        run: |
          export PATH="$HOME/.jbang/bin:$PATH"
          git checkout -b temp-jakarta-rewrite
          REWRITE_NO_TESTS=true ./jakarta/transform.sh
          git add .
          git commit -m 'Transform sources to Jakarta'
          git push --force origin temp-jakarta-rewrite:jakarta-rewrite
        shell: bash
      - name: Adjust version before pushing snapshots
        run: |
          ./update-version.sh 999-jakarta-SNAPSHOT
        shell: bash
      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          ./mvnw -e -B --settings .github/mvn-settings.xml \
            -DskipITs -DskipTests -Dskip.gradle.tests -Dno-format -Dinvoker.skip=true \
            -DretryFailedDeploymentCount=10 \
            -pl !integration-tests/gradle \
            -pl '!:quarkus-integration-test-infinispan-client' -pl '!:quarkus-integration-test-kafka-avro' \
            clean deploy
      - name: Report status
        if: "always() && github.repository == 'quarkusio/quarkus'"
        shell: bash
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          ~/.jbang/bin/jbang .github/NativeBuildReport.java \
            issueNumber=24396 \
            runId=${{ github.run_id }} \
            status=${{ job.status }} \
            token=${{ secrets.GITHUB_API_TOKEN }} \
            issueRepo=${{ github.repository }} \
            thisRepo=${{ github.repository }}
